import {
  BadgeDollarSignIcon,
  BikeIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BusIcon,
  CarIcon,
  CoffeeIcon,
  CreditCardIcon,
  DumbbellIcon,
  FilmIcon,
  FuelIcon,
  Gamepad2Icon,
  GiftIcon,
  GraduationCapIcon,
  HeartIcon,
  HomeIcon,
  LandmarkIcon,
  type LucideIcon,
  MusicIcon,
  PawPrintIcon,
  PhoneIcon,
  PiggyBankIcon,
  PlaneIcon,
  ReceiptIcon,
  ShirtIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SparklesIcon,
  StethoscopeIcon,
  TrendingUpIcon,
  UtensilsIcon,
  WalletIcon,
  WifiIcon,
} from 'lucide-react';

export const CATEGORY_GROUP_COLORS: string[] = [
  '#6366f1',
  '#8b5cf6',
  '#d946ef',
  '#ec4899',
  '#f43f5e',
  '#f97316',
  '#f59e0b',
  '#eab308',
  '#84cc16',
  '#22c55e',
  '#14b8a6',
  '#0ea5e9',
];

export const CATEGORY_GROUP_ICONS: Record<string, LucideIcon> = {
  wallet: WalletIcon,
  home: HomeIcon,
  car: CarIcon,
  fuel: FuelIcon,
  bus: BusIcon,
  bike: BikeIcon,
  plane: PlaneIcon,
  cart: ShoppingCartIcon,
  utensils: UtensilsIcon,
  coffee: CoffeeIcon,
  heart: HeartIcon,
  stethoscope: StethoscopeIcon,
  dumbbell: DumbbellIcon,
  gamepad: Gamepad2Icon,
  film: FilmIcon,
  music: MusicIcon,
  gift: GiftIcon,
  shirt: ShirtIcon,
  graduation: GraduationCapIcon,
  book: BookOpenIcon,
  briefcase: BriefcaseIcon,
  landmark: LandmarkIcon,
  'piggy-bank': PiggyBankIcon,
  'credit-card': CreditCardIcon,
  receipt: ReceiptIcon,
  'trending-up': TrendingUpIcon,
  'badge-dollar': BadgeDollarSignIcon,
  smartphone: SmartphoneIcon,
  phone: PhoneIcon,
  wifi: WifiIcon,
  'paw-print': PawPrintIcon,
  sparkles: SparklesIcon,
};

export const DEFAULT_GROUP_COLOR = CATEGORY_GROUP_COLORS[0];
export const DEFAULT_GROUP_ICON = 'wallet';
